apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.fullname" . }}-gateway
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    gs-service: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "geoserver.selectorLabels" . | nindent 4 }}
    gs-service: gateway
