apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.fullname" . }}-wcs
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    gs-service: wcs
spec:
  type: {{ .Values.wcs.service.type }}
  ports:
    - port: {{ .Values.wcs.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "geoserver.selectorLabels" . | nindent 4 }}
    gs-service: wcs
