version: "3.8"

#
# Configures all geoserver services to use a shared data directory as catalog backend.
# Run with `docker-compose --compatibility -f docker-compose.yml -f docker-compose-shared_datadir.yml up -d`
# NOTE: Not ready for direct usage until deciding on a strategy to easily set up the shared data directory.
#

volumes:
  shared_data_directory:
    driver_opts:
      type: none
      o: bind
      device: $PWD/docker-compose_datadir
  
services:
  database:
    entrypoint: echo "database-service disabled."

  catalog:
    environment:
      BACKEND_JDBCCONFIG: "false"
      BACKEND_DATA_DIRECTORY: "true"
      GEOSERVER_DATA_DIR: /tmp/data_directory
    volumes:
      - shared_data_directory:/tmp/data_directory
    command: echo "catalog-service disabled."

  wfs:
    environment:
      BACKEND_CATALOG: "false"
      BACKEND_DATA_DIRECTORY: "true"
      GEOSERVER_DATA_DIR: /tmp/data_directory
    volumes:
      - shared_data_directory:/tmp/data_directory

  wms:
    environment:
      BACKEND_CATALOG: "false"
      BACKEND_DATA_DIRECTORY: "true"
      GEOSERVER_DATA_DIR: /tmp/data_directory
    volumes:
      - shared_data_directory:/tmp/data_directory

  wcs:
    environment:
      BACKEND_CATALOG: "false"
      BACKEND_DATA_DIRECTORY: "true"
      GEOSERVER_DATA_DIR: /tmp/data_directory
    volumes:
      - shared_data_directory:/tmp/data_directory

  rest:
    environment:
      BACKEND_CATALOG: "false"
      BACKEND_DATA_DIRECTORY: "true"
      GEOSERVER_DATA_DIR: /tmp/data_directory
    volumes:
      - shared_data_directory:/tmp/data_directory

  webui:
    environment:
      BACKEND_CATALOG: "false"
      BACKEND_DATA_DIRECTORY: "true"
      GEOSERVER_DATA_DIR: /tmp/data_directory
    volumes:
      - shared_data_directory:/tmp/data_directory
