version: "3.8"
#
#volumes:

networks:
  gs-cloud-network:
    driver: bridge
        
services:
  # Eureka service discovery. This is a Discovery First Bootstrap configuration.
  # The discovery service is the only fixed entry point.
  # Browse to http://localhost:8761 to check all services are registered.
  # Run docker-compose -f docker-compose.yml -f docker-compose-discovery-ha.yml to run extra discovery service instances for HA
  discovery:
    image: org.geoserver.cloud/gs-cloud-discovery-service:${TAG}
    environment:
      PORT: 8761
      EUREKA_INSTANCE_HOSTNAME: discovery
      JAVA_OPTS: -Xmx256m
    expose: 
      - 8761
    ports:
      - "8761:8761" # for development, so services can be run from localhost and find the discovery service running on docker
    networks:
      - gs-cloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-m", "1", "http://localhost:8761/actuator/health"]
      interval: 1s
      timeout: 1s
      retries: 15

  # Spring Cloud Config service, provides centralized configuration to all
  # microservices. Being a Discovery First Bootstrap configuration, it'll
  # register itself with the Eureka discovery service and can be scaled
  config:
    image: org.geoserver.cloud/gs-cloud-config-service:${TAG}
    depends_on:
      - discovery
    environment:
      PORT: ${CONFIG_PORT}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      JAVA_OPTS: -Xmx256m
    expose:
      - ${CONFIG_PORT}
    networks:
      - gs-cloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-m", "1", "http://localhost:${CONFIG_PORT}/actuator/health"]
      interval: 1s
      timeout: 1s
      retries: 15
    # wait until discovery service is available
    command: dockerize -wait http://discovery:8761/actuator/health --timeout 15s java $JAVA_OPTS -jar /opt/config-service.jar

  # Application facade, provides a single entry point routing to all
  # microservices (e.g. http://localhost:9090/geoserver/wms, http://localhost:9090/geoserver/wfs, etc)
  gateway:
    image: org.geoserver.cloud/gs-cloud-gateway:${TAG}
    depends_on:
      - discovery
      - config
    environment:
      PORT: ${GATEWAY_PORT}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      JAVA_OPTS: -Xmx256m
    expose: 
      - ${GATEWAY_PORT}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    networks:
      - gs-cloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
    # wait until config service is available
    command: dockerize -wait http://config:${CONFIG_PORT}/gateway-service/deafult --timeout 15s java $JAVA_OPTS -jar /opt/gateway-service.jar

  # WFS microservice, port dynamically allocated to allow scaling (e.g docker-compose scale wfs=5)
  wfs:
    image: org.geoserver.cloud/gs-cloud-wfs:${TAG}
    depends_on:
      - discovery
      - config
    environment:
      PORT: ${WFS_PORT}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      JAVA_OPTS: -Xmx512m
    networks:
      - gs-cloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WFS_PORT}/actuator/health"]
    # wait until config service is available
    command: dockerize -wait http://config:${CONFIG_PORT}/wfs-service/deafult --timeout 15s java $JAVA_OPTS -jar /opt/wfs-service.jar

  # WMS microservice, port dynamically allocated to allow scaling (e.g docker-compose scale wms=5)
  wms:
    image: org.geoserver.cloud/gs-cloud-wms:${TAG}
    depends_on:
      - discovery
      - config
    environment:
      PORT: ${WMS_PORT}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      JAVA_OPTS: -Xmx512m
    networks:
      - gs-cloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WMS_PORT}/actuator/health"]
    # wait until config service is available
    command: dockerize -wait http://config:${CONFIG_PORT}/wms-service/deafult --timeout 15s java $JAVA_OPTS -jar /opt/wms-service.jar

  # WCS microservice, port dynamically allocated to allow scaling (e.g docker-compose scale wcs=5)
  wcs:
    image: org.geoserver.cloud/gs-cloud-wcs:${TAG}
    depends_on:
      - discovery
      - config
    environment:
      PORT: ${WCS_PORT}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      JAVA_OPTS: -Xmx512m
    networks:
      - gs-cloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WCS_PORT}/actuator/health"]
    # wait until config service is available
    command: dockerize -wait http://config:${CONFIG_PORT}/wcs-service/deafult --timeout 15s java $JAVA_OPTS -jar /opt/wcs-service.jar

  # WPS microservice, port dynamically allocated to allow scaling (e.g docker-compose scale wps=5)
  wps:
    image: org.geoserver.cloud/gs-cloud-wps:${TAG}
    depends_on:
      - discovery
      - config
    environment:
      PORT: ${WPS_PORT}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      JAVA_OPTS: -Xmx512m
    networks:
      - gs-cloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WPS_PORT}/actuator/health"]
    # wait until config service is available
    command: dockerize -wait http://config:${CONFIG_PORT}/wps-service/deafult --timeout 15s java $JAVA_OPTS -jar /opt/wps-service.jar

  # WPS microservice, port dynamically allocated to allow scaling (e.g docker-compose scale wps=5)
  rest:
    image: org.geoserver.cloud/gs-cloud-restconfig-v1:${TAG}
    depends_on:
      - discovery
      - config
    environment:
      PORT: ${REST_PORT}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      JAVA_OPTS: -Xmx256m
    networks:
      - gs-cloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${REST_PORT}/actuator/health"]
    # wait until config service is available
    command: dockerize -wait http://config:${CONFIG_PORT}/restconfig-service/deafult --timeout 15s java $JAVA_OPTS -jar /opt/restconfig-service.jar
