version: "3.8"

#
# Configures all geoserver services to use the postgresql database server with jdbcconfig as catalog backend.
# Run with `docker-compose --compatibility -f docker-compose.yml -f docker-compose-jdbcconfig.yml up -d`
#

services:
  catalog:
    environment:
      BACKEND_CATALOG: "false"
      BACKEND_DATA_DIRECTORY: "false"
      BACKEND_JDBCCONFIG: "true"
      JDBCCONFIG_URL: "${JDBCCONFIG_URL}"
      JDBCCONFIG_USERNAME: "${JDBCCONFIG_USERNAME}"
      JDBCCONFIG_PASSWORD: "${JDBCCONFIG_PASSWORD}"
    command: echo "catalog-service disabled."

  wfs:
    environment:
      BACKEND_CATALOG: "false"
      BACKEND_DATA_DIRECTORY: "false"
      BACKEND_JDBCCONFIG: "true"
      JDBCCONFIG_URL: "${JDBCCONFIG_URL}"
      JDBCCONFIG_USERNAME: "${JDBCCONFIG_USERNAME}"
      JDBCCONFIG_PASSWORD: "${JDBCCONFIG_PASSWORD}"

  wms:
    environment:
      BACKEND_CATALOG: "false"
      BACKEND_DATA_DIRECTORY: "false"
      BACKEND_JDBCCONFIG: "true"
      JDBCCONFIG_URL: "${JDBCCONFIG_URL}"
      JDBCCONFIG_USERNAME: "${JDBCCONFIG_USERNAME}"
      JDBCCONFIG_PASSWORD: "${JDBCCONFIG_PASSWORD}"

  wcs:
    environment:
      BACKEND_CATALOG: "false"
      BACKEND_DATA_DIRECTORY: "false"
      BACKEND_JDBCCONFIG: "true"
      JDBCCONFIG_URL: "${JDBCCONFIG_URL}"
      JDBCCONFIG_USERNAME: "${JDBCCONFIG_USERNAME}"
      JDBCCONFIG_PASSWORD: "${JDBCCONFIG_PASSWORD}"

  rest:
    environment:
      BACKEND_CATALOG: "false"
      BACKEND_DATA_DIRECTORY: "false"
      BACKEND_JDBCCONFIG: "true"
      JDBCCONFIG_URL: "${JDBCCONFIG_URL}"
      JDBCCONFIG_USERNAME: "${JDBCCONFIG_USERNAME}"
      JDBCCONFIG_PASSWORD: "${JDBCCONFIG_PASSWORD}"

  webui:
    environment:
      BACKEND_CATALOG: "false"
      BACKEND_DATA_DIRECTORY: "false"
      BACKEND_JDBCCONFIG: "true"
      JDBCCONFIG_URL: "${JDBCCONFIG_URL}"
      JDBCCONFIG_USERNAME: "${JDBCCONFIG_USERNAME}"
      JDBCCONFIG_PASSWORD: "${JDBCCONFIG_PASSWORD}"
