server:
   port: ${PORT:9090}

management:
  endpoint:
    gateway:
      enabled: true # default value
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, info, health

spring:  
  cloud:
    gateway:
      actuator:
        verbose:
          enabled: true
      # Configure routes to services. See https://cloud.spring.io/spring-cloud-gateway/single/spring-cloud-gateway.html
      routes:
      # WFS routes
      - id: wfs # proxies requests to api-gateway:/wfs to wfs-service:/wfs
        uri: lb://wfs #load balanced to the wfs service instances
        predicates:
        - Path=/wfs
        - Path=/wfs/**
        filters:
        - RewritePath=/(?<wfs>.*), /$\{wfs}
      # WMS routes
      - id: wms # proxies requests to api-gateway:/wms to wms:/wms
        uri: lb://wms #load balanced to the wms service instances
        predicates:
        - Path=/wms
        - Path=/wms/**
        filters:
        - RewritePath=/(?<wms>.*), /$\{wms}
#        - AddResponseHeader=X-Some-Header, aboullaite.me
      # WCS routes
      - id: wcs # proxies requests to api-gateway:/wfs to wfs:/wfs
        uri: lb://wcs #load balanced to the wcs instances
        predicates:
        - Path=/wcs
        - Path=/wcs/**
        filters:
        - RewritePath=/(?<wcs>.*), /$\{wcs}
      # WPS routes
      - id: wps # proxies requests to api-gateway:/wps to wps:/wps
        uri: lb://wps #load balanced to the wps instances
        predicates:
        - Path=/wps
        - Path=/wps/**
        filters:
        - RewritePath=/(?<wps>.*), /$\{wps}
      # REST configuration routes
      - id: restconfig
        uri: lb://restconfig-v1 #load balanced to the restconfig-v1 instances
        predicates:
        - Path=/rest
        - Path=/rest/**
        filters:
        - RewritePath=/(?<rest>.*), /$\{rest}

logging:
  level:
    root: ERROR
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
