server:
   port: ${PORT:9090}

management:
  endpoint:
    gateway:
      enabled: true # default value
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, info, health

spring:  
  cloud:
    gateway:
      actuator:
        verbose:
          enabled: true
      # Configure routes to services. See https://cloud.spring.io/spring-cloud-gateway/single/spring-cloud-gateway.html
      routes:
      # WFS routes
      - id: wfs # proxies requests to gateway-service:/wfs to wfs-service:/wfs
        uri: lb://wfs-service #load balanced to the wfs-service instances
        predicates:
        - Path=/wfs,/schemas/wfs/**
        #filters:
        #- RewritePath=/(?<wfs>.*), /$\{wfs}
      # WMS routes
      - id: wms # proxies requests to gateway-service:/wms to wms-service:/wms
        uri: lb://wms-service #load balanced to the wms-service instances
        predicates:
        - Path=/wms,/schemas/wms/**,/openlayers/**,/openlayers3/**
#        filters:
#        - RewritePath=/(?<wms>.*), /$\{wms}
#        - AddResponseHeader=X-Some-Header, aboullaite.me
      # WCS routes
      - id: wcs # proxies requests to gateway-service:/wcs to wcs-service:/wcs
        uri: lb://wcs-service #load balanced to the wps-service instances
        predicates:
        - Path=/wcs,/schemas/wcs/**
#        filters:
#        - RewritePath=/(?<wcs>.*), /$\{wcs}
      # WPS routes
      - id: wps # proxies requests to gateway-service:/wps to wfs-service:/wps
        uri: lb://wps-service #load balanced to the wps-service instances
        predicates:
        - Path=/wps,/schemas/wps/**
#        filters:
#        - RewritePath=/(?<wps>.*), /$\{wps}
      # REST configuration routes
      - id: restconfig
        uri: lb://restconfig-v1 #load balanced to the restconfig-v1 instances
        predicates:
        - Path=/rest/**
#        filters:
#         - RewritePath=/rest/(?<segment>.*), /rest/$\{segment}

logging:
  level:
    root: ERROR
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
