geoserver:
  jdbcconfig:
    enabled: true
    datasource:
      jdbcUrl: ${jdbcconfig.url:"jdbc:postgresql://localhost:5432/geoserver_config"}
      username: ${jdbcconfig.username:postgres}
      password: ${jdbcconfig.password:s3cr3t}
      driverClassname: ${jdbcconfig.driverClassname:org.postgresql.Driver}
logging:
  level:
    org.springframework: ERROR
    oshi.hardware.platform.linux: OFF
    org.geoserver.jdbcconfig: INFO
    org.geoserver.jdbcconfig.internal: INFO