geoserver:
  catalog:
    data-directory: ${java.io.tmpdir}/empty_data_directory
  catalog-service:
    worker-threads:
      max-size: 8
      max-queued: 10000
  servlet.filter.session-debug.enabled: false # until the NPE is fixed
  jdbcconfig:
    enabled: true
    web.enabled: false
    datasource:
      jdbcUrl: ${jdbcconfig.url:"jdbc:postgresql://database:5432/geoserver_config"}
      username: ${jdbcconfig.username:geoserver}
      password: ${jdbcconfig.password:geo$erver}
      driverClassname: ${jdbcconfig.driverClassname:org.postgresql.Driver}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_URSER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  cloud:
    bus:
      enabled: true
      id: ${server.instance-id} # use the same instance id for eureka (see service's' bootstrap.yml) and cloud-bus' rabbitmq instance id
      trace.enabled: true #switch on tracing of acks (default off).
    stream:
      bindings:
        springCloudBusOutput:
          destination: gscatalog
        springCloudBusInput:
          destination: gscatalog

logging:
  level:
#      org.springframework: ERROR
    org.geoserver.cloud: DEBUG
    org.geoserver.cloud.autoconfigure: DEBUG
    oshi.hardware.platform.linux: OFF
    org.geoserver.jdbcconfig: INFO
    org.geoserver.jdbcconfig.internal: INFO
    org.springframework.context.support.PostProcessorRegistrationDelegate: WARN
