geoserver:
  security.enabled: true
  servlet.filter.session-debug.enabled: false # until the NPE is fixed
  catalog:
    advertised: true
    localWorkspace: true
    secure: true
  bus:
    send-object: false
    send-diff: false
  backend:
    data-directory:
      enabled: false
      location: ${GEOSERVER_DATA_DIR:${java.io.tmpdir}/default_data_directory} 
    jdbcconfig:
      enabled: true
      initdb: false
      web.enabled: true
      cache-directory: ${jdbcconfig.cachedir:${java.io.tmpdir}/geoserver-jdbcconfig-cache}
      datasource:
        jdbcUrl: ${jdbcconfig.url:"jdbc:postgresql://database:5432/geoserver_config"}
        username: ${jdbcconfig.username:geoserver}
        password: ${jdbcconfig.password:geo$erver}
        driverClassname: ${jdbcconfig.driverClassname:org.postgresql.Driver}
        # optional:
        schema: public
        minimumIdle: 2
        maximumPoolSize: 8
  web-ui:
    # Theese are all default values, here just for reference. You can omit them and add only the ones to disable or further configure
    security.enabled: true
    wfs.enabled: true
    wms.enabled: true
    wcs.enabled: true
    wps.enabled: true
    gwc.enabled: false # not ready yet
    extensions:
      importer.enabled: true
    demos:
      enabled: true
      wps-request-builder: true
      wcs-request-builder: true
      demo-requests: true
      srs-list: true
      reprojection-console: true
      layer-preview-page:
        enabled: true
        common-formats:
          open-layers: true
          gml: true
          kml: true
    tools:
      enabled: true
      resource-browser: true
      catalog-bulk-load: true
    
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_URSER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  cloud:
    bus:
      enabled: true
      id: ${server.instance-id} # use the same instance id for eureka (see service's' bootstrap.yml) and cloud-bus' rabbitmq instance id
      trace.enabled: true #switch on tracing of acks (default off).
    stream:
      bindings:
        springCloudBusOutput:
          destination: gscatalog
        springCloudBusInput:
          destination: gscatalog

logging:
  level:
    root: WARN
    org.springframework: ERROR
    org.springframework.cloud.bus: INFO
    # geoserver roots
    org.geoserver.platform: ERROR
    org.geoserver.jdbcconfig: INFO
    oshi.hardware.platform.linux: ERROR
    oshi.software.os: ERROR
    # gs-cloud roots
    org.geoserver.cloud: INFO
    org.geoserver.cloud.autoconfigure: INFO
    org.geoserver.cloud.config.factory: INFO
    # bus debugging
    org.geoserver.cloud.bus: INFO
    org.springframework.cloud.bus.BusAutoConfiguration: INFO
    org.springframework.cloud.bus.DefaultBusPathMatcher: INFO
