apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geoserver.fullname" . }}-config
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    gs-service: "config"
spec:
  replicas: {{ .Values.config.replicaCount }}
  selector:
    matchLabels:
      {{- include "geoserver.selectorLabels" . | nindent 6 }}
      gs-service: "config"
  template:
    metadata:
    {{- with .Values.config.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "geoserver.selectorLabels" . | nindent 8 }}
        gs-service: "config"
    spec:
      serviceAccountName: {{ include "geoserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.config.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-config
          securityContext:
            {{- toYaml .Values.config.securityContext | nindent 12 }}
          image: "{{ .Values.config.image.repository }}:{{ .Values.config.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.config.image.pullPolicy }}
          command:
          {{- range $cmd := .Values.config.command }}
            - {{ $cmd }}
          {{- end }}
          env:
            - name: CONFIG_PATH
              value: /opt/app/config
{{ toYaml .Values.config.env | indent 12 }}

          volumeMounts:
            - name: configs
              mountPath: /opt/app/config

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5

          resources:
            {{- toYaml .Values.config.resources | nindent 12 }}
      volumes:
        - name: configs
          configMap:
            name: {{ include "geoserver.fullname" . }}-config-configs
      {{- with .Values.config.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.config.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.config.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
