apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.fullname" . }}-webui
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    gs-service: webui
spec:
  type: {{ .Values.webui.service.type }}
  ports:
    - port: {{ .Values.webui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "geoserver.selectorLabels" . | nindent 4 }}
    gs-service: webui
