apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geoserver.fullname" . }}-discovery
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    gs-service: discovery
spec:
  replicas: {{ .Values.discovery.replicaCount }}
  selector:
    matchLabels:
      {{- include "geoserver.selectorLabels" . | nindent 6 }}
      gs-service: discovery
  template:
    metadata:
    {{- with .Values.discovery.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "geoserver.selectorLabels" . | nindent 8 }}
        gs-service: discovery
    spec:
      serviceAccountName: {{ include "geoserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.discovery.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-discovery
          securityContext:
            {{- toYaml .Values.discovery.securityContext | nindent 12 }}
          image: "{{ .Values.discovery.image.repository }}:{{ .Values.discovery.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.discovery.image.pullPolicy }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: geoserver-discovery
            - name: SERVER_PORT
              value: "8761"
{{ toYaml .Values.discovery.env | indent 12 }}

          ports:
            - name: http
              containerPort: 8761
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http

          resources:
            {{- toYaml .Values.discovery.resources | nindent 12 }}
      {{- with .Values.discovery.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.discovery.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.discovery.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
