apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geoserver.fullname" . }}-wms
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    gs-service: wms
spec:
  replicas: {{ .Values.wms.replicaCount }}
  selector:
    matchLabels:
      {{- include "geoserver.selectorLabels" . | nindent 6 }}
      gs-service: wms
  template:
    metadata:
    {{- with .Values.wms.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "geoserver.selectorLabels" . | nindent 8 }}
        gs-service: wms
    spec:
      serviceAccountName: {{ include "geoserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.wms.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-wms
          securityContext:
            {{- toYaml .Values.wms.securityContext | nindent 12 }}
          image: "{{ .Values.wms.image.repository }}:{{ .Values.wms.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.wms.image.pullPolicy }}
          command:
          {{- range $cmd := .Values.wms.command }}
            - {{ $cmd }}
          {{- end }}
          env:
            - name: JDBCCONFIG_URL
              value: {{ .Values.jdbcconfig.url }}
            - name: JDBCCONFIG_USERNAME
              value: {{ .Values.jdbcconfig.username }}
            - name: JDBCCONFIG_PASSWORD
              value: {{ .Values.jdbcconfig.password }}
{{ toYaml .Values.wms.env | indent 12 }}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 5

          resources:
            {{- toYaml .Values.wms.resources | nindent 12 }}
      {{- with .Values.wms.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wms.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wms.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
