# Builds and pushes docker images on main and tags

name: Build and Push Docker images
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: Build and Push
    runs-on:
      - ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Validate source code formatting
      run: ./mvnw fmt:check -ntp

    - name: Build GeoServer 2.21-CLOUD
      run: |
        git clone --depth 1 --branch geoserver-cloud_integration https://github.com/groldan/geoserver.git
        ./mvnw -f ./geoserver/src/ install -PallExtensions,communityRelease --no-transfer-progress -DskipTests -Dfmt.skip -T1C 

    - name: Build and push Hotspot and OpenJ9 docker images
      run: ./mvnw -Ddockerfile.push.skip=false  install \
           -ntp -Dfmt.skip -T1 -DskipTests

    - name: Remove project jars from cached repository
      run: |
        rm -rf .m2/repository/org/geoserver/cloud
        rm -rf .m2/repository/org/geoserver/
        