# Builds and pushes docker images on main and tags

name: Build and Push Docker images
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: Build and Push
    runs-on:
      - ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Checkout project
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Fetch maven cache
      uses: actions/cache@v1.1.0
      with:
        path: ~/.m2/repository
        key: gscloud-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gscloud-${{ runner.os }}-maven-

    - name: Clone GeoServer
      run: |
        git clone --depth 1 --branch geoserver-cloud_integration https://github.com/groldan/geoserver.git

    - name: Build GeoServer 2.21-CLOUD
      run: |
        ./mvnw -f ./geoserver/src/ versions:set -DnewVersion=2.21-CLOUD -PallExtensions,communityRelease install --no-transfer-progress -DskipTests -Dfmt.skip -T1C 
        ./mvnw -f ./geoserver/src/ install -PallExtensions,communityRelease --no-transfer-progress -DskipTests -Dfmt.skip -T1 

    - name: Update maven dependencies
      run: ./mvnw -Dgs.version=2.21-CLOUD -Dgs.community.version=2.21-CLOUD -P\!docker de.qaware.maven:go-offline-maven-plugin:resolve-dependencies --no-transfer-progress

    - name: Build and push docker images
      run: ./mvnw -Dgs.version=2.21-CLOUD -Dgs.community.version=2.21-CLOUD -Pdocker -Ddockerfile.push.skip=false -ntp -Dfmt.skip install -T1 -DskipTests

    - name: Remove project jars from cached repository
      run: |
        rm -rf .m2/repository/org/geoserver/cloud
        rm -rf .m2/repository/org/geoserver/
        