# Builds and pushes docker images on main and tags

name: Build and Push Docker images
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: Build and Push
    runs-on: [ubuntu-latest]
    timeout-minutes: 60
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Checkout project
      uses: actions/checkout@v1

    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Fetch maven cache
      uses: actions/cache@v1.1.0
      with:
        path: ~/.m2/repository
        key: gscloud-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gscloud-${{ runner.os }}-maven-

    - name: Update maven dependencies
      run: ./mvnw -P\!docker de.qaware.maven:go-offline-maven-plugin:resolve-dependencies --no-transfer-progress

    - name: Build base java image
      run: ./mvnw dockerfile:build -f docker-base-java/

    - name: Build and push docker images
      run: ./mvnw -Pdocker -Ddockerfile.push.skip=false -ntp -Dfmt.skip install -T1C -DskipTests

    - name: Remove project jars from cached repository
      run: |
        rm -rf .m2/repository/org/geoserver/cloud
