# Triggers the workflow on pull request events to the main branch
name: Pull Request on Main Branch
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test 
    runs-on:
      - ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Validate source code formatting
      run: ./mvnw fmt:check -ntp

    - name: Build GeoServer 2.21-CLOUD
      run: |
        git clone --depth 1 --branch geoserver-cloud_integration https://github.com/groldan/geoserver.git
        ./mvnw -f ./geoserver/src/ install -PallExtensions,communityRelease --no-transfer-progress -DskipTests -Dfmt.skip -T1C 

    - name: Build without tests
      run: ./mvnw -P-docker,-docker-openj9 -ntp -Dfmt.skip install -T1C -DskipTests

    - name: Test
      run: ./mvnw -P-docker,-docker-openj9 -ntp verify -T1C -fae

    - name: Remove project jars from cached repository
      run: |
        rm -rf .m2/repository/org/geoserver/cloud
        rm -rf .m2/repository/org/geoserver
        